// =========================================================================
// HỆ THỐNG TOÀN BỘ CÁC TỔ HỢP MÔN THI (DÙNG CHUNG)
// =========================================================================
const COMBINATIONS_DB = {
    // Khối A và các biến thể
    "A00": ["m-toan", "m-ly", "m-hoa"],
    "A01": ["m-toan", "m-ly", "m-anh"],
    "A02": ["m-toan", "m-ly", "m-sinh"],
    "A03": ["m-toan", "m-ly", "m-van"],
    "A04": ["m-toan", "m-ly", "m-dia"],
    "A05": ["m-toan", "m-hoa", "m-lich-su"],
    "A06": ["m-toan", "m-hoa", "m-dia"],
    "A07": ["m-toan", "m-lich-su", "m-dia"],
    "A08": ["m-toan", "m-lich-su", "m-gdktdpl"],
    "A09": ["m-toan", "m-dia", "m-gdktdpl"],
    "A10": ["m-toan", "m-ly", "m-gdktdpl"],
    "A11": ["m-toan", "m-hoa", "m-gdktdpl"],
    "A12": ["m-toan", "m-khoa-hoc-tu-nhien", "m-van"],
    "A14": ["m-toan", "m-khoa-hoc-tu-nhien", "m-dia"],
    "A15": ["m-toan", "m-khoa-hoc-tu-nhien", "m-gdktdpl"],
    "A16": ["m-toan", "m-khoa-hoc-tu-nhien", "m-van"],
    "A17": ["m-toan", "m-ly", "m-tin"],
    "A18": ["m-toan", "m-hoa", "m-tin"],

    // Khối B và các biến thể
    "B00": ["m-toan", "m-hoa", "m-sinh"],
    "B01": ["m-toan", "m-sinh", "m-lich-su"],
    "B02": ["m-toan", "m-sinh", "m-dia"],
    "B03": ["m-toan", "m-sinh", "m-van"],
    "B04": ["m-toan", "m-sinh", "m-gdktdpl"],
    "B05": ["m-toan", "m-sinh", "m-khoa-hoc-xa-hoi"],
    "B08": ["m-toan", "m-sinh", "m-anh"],

    // Khối C và các biến thể
    "C00": ["m-van", "m-lich-su", "m-dia"],
    "C01": ["m-toan", "m-van", "m-ly"],
    "C02": ["m-toan", "m-van", "m-hoa"],
    "C03": ["m-toan", "m-van", "m-lich-su"],
    "C04": ["m-toan", "m-van", "m-dia"],
    "C05": ["m-toan", "m-van", "m-hoa"],
    "C06": ["m-toan", "m-van", "m-sinh"],
    "C07": ["m-van", "m-ly", "m-hoa"],
    "C08": ["m-van", "m-hoa", "m-sinh"],
    "C09": ["m-van", "m-ly", "m-dia"],
    "C10": ["m-van", "m-ly", "m-lich-su"],
    "C12": ["m-van", "m-sinh", "m-lich-su"],
    "C13": ["m-van", "m-sinh", "m-dia"],
    "C14": ["m-toan", "m-van", "m-gdktdpl"],
    "C15": ["m-toan", "m-van", "m-khoa-hoc-xa-hoi"],
    "C16": ["m-van", "m-vat-ly", "m-gdktdpl"],
    "C17": ["m-van", "m-hoa-hoc", "m-gdktdpl"],
    "C19": ["m-van", "m-lich-su", "m-gdktdpl"],
    "C20": ["m-van", "m-dia-ly", "m-gdktdpl"],

    // Khối D và các mã ngoại ngữ từ D01 - D96
    "D01": ["m-toan", "m-van", "m-anh"],
    "D02": ["m-toan", "m-van", "m-nga"],
    "D03": ["m-toan", "m-van", "m-phap"],
    "D04": ["m-toan", "m-van", "m-trung"],
    "D05": ["m-toan", "m-van", "m-duc"],
    "D06": ["m-toan", "m-van", "m-nhat"],
    "D07": ["m-toan", "m-hoa", "m-anh"],
    "D08": ["m-toan", "m-sinh", "m-anh"],
    "D09": ["m-toan", "m-lich-su", "m-anh"],
    "D10": ["m-toan", "m-dia", "m-anh"],
    "D11": ["m-van", "m-vat-ly", "m-anh"],
    "D12": ["m-van", "m-hoa-hoc", "m-anh"],
    "D13": ["m-van", "m-sinh-hoc", "m-anh"],
    "D14": ["m-van", "m-lich-su", "m-anh"],
    "D15": ["m-van", "m-dia-ly", "m-anh"],
    "D16": ["m-toan", "m-dia-ly", "m-duc"],
    "D17": ["m-toan", "m-dia-ly", "m-nga"],
    "D18": ["m-toan", "m-dia-ly", "m-nhat"],
    "D19": ["m-toan", "m-dia-ly", "m-phap"],
    "D20": ["m-toan", "m-dia", "m-gdktdpl"],
    "D21": ["m-toan", "m-dia-ly", "m-trung"],
    "D22": ["m-toan", "m-gdktdpl", "m-duc"],
    "D23": ["m-toan", "m-gdktdpl", "m-nga"],
    "D24": ["m-toan", "m-gdktdpl", "m-nhat"],
    "D25": ["m-toan", "m-gdktdpl", "m-phap"],
    "D26": ["m-toan", "m-vat-ly", "m-duc"],
    "D27": ["m-toan", "m-vat-ly", "m-nga"],
    "D28": ["m-toan", "m-vat-ly", "m-nhat"],
    "D29": ["m-toan", "m-vat-ly", "m-phap"],
    "D30": ["m-toan", "m-vat-ly", "m-trung"],
    "D41": ["m-toan", "m-gdktdpl", "m-trung"],
    "D42": ["m-toan", "m-hoa-hoc", "m-duc"],
    "D43": ["m-toan", "m-hoa-hoc", "m-nga"],
    "D44": ["m-toan", "m-hoa-hoc", "m-nhat"],
    "D45": ["m-toan", "m-hoa-hoc", "m-phap"],
    "D46": ["m-toan", "m-hoa-hoc", "m-trung"],
    "D51": ["m-toan", "m-sinh-hoc", "m-duc"],
    "D52": ["m-toan", "m-sinh-hoc", "m-nga"],
    "D53": ["m-toan", "m-sinh-hoc", "m-nhat"],
    "D54": ["m-toan", "m-sinh-hoc", "m-phap"],
    "D55": ["m-toan", "m-sinh-hoc", "m-trung"],
    "D61": ["m-toan", "m-lich-su", "m-duc"],
    "D62": ["m-toan", "m-lich-su", "m-nga"],
    "D63": ["m-toan", "m-lich-su", "m-nhat"],
    "D64": ["m-toan", "m-lich-su", "m-phap"],
    "D65": ["m-toan", "m-lich-su", "m-trung"],
    "D66": ["m-van", "m-gdktdpl", "m-anh"],
    "D68": ["m-van", "m-gdktdpl", "m-nga"],
    "D69": ["m-van", "m-gdktdpl", "m-phap"],
    "D70": ["m-van", "m-gdktdpl", "m-trung"],
    "D72": ["m-van", "m-khoa-hoc-tu-nhien", "m-anh"],
    "D73": ["m-van", "m-khoa-hoc-tu-nhien", "m-duc"],
    "D74": ["m-van", "m-khoa-hoc-tu-nhien", "m-nga"],
    "D75": ["m-van", "m-khoa-hoc-tu-nhien", "m-nhat"],
    "D76": ["m-van", "m-khoa-hoc-tu-nhien", "m-phap"],
    "D77": ["m-van", "m-khoa-hoc-tu-nhien", "m-trung"],
    "D78": ["m-van", "m-khoa-hoc-xa-hoi", "m-anh"],
    "D79": ["m-van", "m-khoa-hoc-xa-hoi", "m-duc"],
    "D80": ["m-van", "m-khoa-hoc-xa-hoi", "m-nga"],
    "D81": ["m-van", "m-khoa-hoc-xa-hoi", "m-nhat"],
    "D82": ["m-van", "m-khoa-hoc-xa-hoi", "m-phap"],
    "D83": ["m-van", "m-khoa-hoc-xa-hoi", "m-trung"],
    "D84": ["m-toan", "m-gdktdpl", "m-anh"],
    "D85": ["m-toan", "m-gdktdpl", "m-duc"],
    "D86": ["m-toan", "m-gdktdpl", "m-nga"],
    "D87": ["m-toan", "m-gdktdpl", "m-nhat"],
    "D88": ["m-toan", "m-gdktdpl", "m-phap"],
    "D90": ["m-toan", "m-khoa-hoc-tu-nhien", "m-anh"],
    "D91": ["m-toan", "m-khoa-hoc-tu-nhien", "m-phap"],
    "D95": ["m-toan", "m-khoa-hoc-tu-nhien", "m-trung"],
    "D96": ["m-toan", "m-khoa-hoc-xa-hoi", "m-anh"],

    // Các tổ hợp đặc thù/mới bổ sung (Khối X, Năng khiếu, Tin học...)
    "X01": ["m-van", "m-lich-su", "m-dia"],
    "X02": ["m-toan", "m-van", "m-lich-su"],
    "X06": ["m-toan", "m-van", "m-ly"],
    "X25": ["m-toan", "m-anh", "m-gdktdpl"],
    "X26": ["m-toan", "m-anh", "m-tin"],
    "M01": ["m-van", "m-toan", "m-nang-khieu-1"],
    "M02": ["m-van", "m-nang-khieu-1", "m-nang-khieu-2"],
    "N01": ["m-van", "m-nang-khieu-am-nhac-1", "m-nang-khieu-am-nhac-2"],
    "H00": ["m-van", "m-nang-khieu-ve-1", "m-nang-khieu-ve-2"],
    "H01": ["m-toan", "m-van", "m-nang-khieu-ve"],
    "T00": ["m-toan", "m-sinh", "m-nang-khieu-tdtt"],
    "V00": ["m-toan", "m-ly", "m-nang-khieu-ve-mt"],
    "V01": ["m-toan", "m-van", "m-nang-khieu-ve-mt"]
};

// Map nhanh khối thi với loại tiếng tương ứng để thuật toán xét chứng chỉ chạy tự động
const CONFIG_LANGUAGE_SUBJECTS = {
    "A01": "m-anh", "D01": "m-anh", "D07": "m-anh", "D08": "m-anh", "D09": "m-anh", "D10": "m-anh",
    "D11": "m-anh", "D12": "m-anh", "D13": "m-anh", "D14": "m-anh", "D15": "m-anh", "D66": "m-anh",
    "D72": "m-anh", "D78": "m-anh", "D84": "m-anh", "D90": "m-anh", "D96": "m-anh", "X25": "m-anh", "X26": "m-anh",
    "D02": "m-nga", "D17": "m-nga", "D23": "m-nga", "D27": "m-nga", "D43": "m-nga", "D52": "m-nga", "D62": "m-nga", "D68": "m-nga", "D74": "m-nga", "D80": "m-nga", "D86": "m-nga",
    "D03": "m-phap", "D19": "m-phap", "D25": "m-phap", "D29": "m-phap", "D45": "m-phap", "D54": "m-phap", "D64": "m-phap", "D69": "m-phap", "D76": "m-phap", "D82": "m-phap", "D88": "m-phap", "D91": "m-phap",
    "D04": "m-trung", "D21": "m-trung", "D30": "m-trung", "D41": "m-trung", "D46": "m-trung", "D55": "m-trung", "D65": "m-trung", "D70": "m-trung", "D77": "m-trung", "D83": "m-trung", "D95": "m-trung",
    "D05": "m-duc", "D16": "m-duc", "D22": "m-duc", "D26": "m-duc", "D42": "m-duc", "D51": "m-duc", "D61": "m-duc", "D73": "m-duc", "D79": "m-duc", "D85": "m-duc",
    "D06": "m-nhat", "D18": "m-nhat", "D24": "m-nhat", "D28": "m-nhat", "D44": "m-nhat", "D53": "m-nhat", "D63": "m-nhat", "D75": "m-nhat", "D81": "m-nhat", "D87": "m-nhat"
};

// Khởi tạo các đối tượng trống toàn cục để các file trường tự đổ dữ liệu vào
const UNIVERSITY_DATABASE = {};
const UNIVERSITY_CERTIFICATES = {};
